apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    app: {{ include "redis.name" . }}
    chart: {{ include "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  redis.conf: |
    # Network
    bind 0.0.0.0
    port {{ .Values.service.targetport }}
    protected-mode yes

    # TLS/SSL
    tls-port 0
    tls-cert-file ""
    tls-key-file ""
    tls-auth-clients no

    # Performance Tuning
    timeout 0
    tcp-keepalive 300
    databases 16

    # Memory Management
    maxmemory 512mb
    maxmemory-policy allkeys-lru

    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data

    # Security
    requirepass {{ .Values.redis.auth.password }}

    # Clients
    maxclients 10000

    # Append Only Mode
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec

    # Logging
    loglevel notice
    logfile "/data/redis.log"
