"""test

Revision ID: e978ec483291
Revises: 5d6e98c48a7a
Create Date: 2025-01-09 14:07:01.371472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e978ec483291'
down_revision = '5d6e98c48a7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
