apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
data:
  DATABASE__URL: {{ .Values.secret.DATABASE__URL | b64enc }}
  REDIS__PASSWORD: {{ .Values.secret.REDIS__PASSWORD | b64enc }}
