# helm/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  labels:
    app: {{ include "grafana.name" . }}
    chart: {{ include "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc }}
  admin-password: {{ .Values.adminPassword | b64enc }}
