# helm/prometheus/values.yaml
replicaCount: 1

image:
  repository: prom/prometheus
  tag: "v2.31.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090
  targetport: 9090

resources:
  requests:
    memory: "1256Mi"
    cpu: "1200m"
  limits:
    memory: "1356Mi"
    cpu: "1300m"

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 30Gi
  storageClassName: default

nodeSelector: {}

tolerations: []

affinity: {}
