apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ template "tempo.name" . }}
    chart: {{ template "tempo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.otlpGrpc }}
      targetPort: {{ .Values.service.ports.otlpGrpc }}
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.service.ports.otlpHttp }}
      targetPort: {{ .Values.service.ports.otlpHttp }}
      protocol: TCP
      name: otlp-http
  selector:
    app: {{ include "tempo.name" . }}
    release: {{ .Release.Name }}
